### ISSUE TITLE
specify replica count

### ISSUE THREAD

**Issue by ngtuna** [skippbox/kompose2#15]
It should be very easy to do `kompose convert --replica <number>`

**Comment by runseb** [comment]
Why do you want to do this ?
convert creates the objects, we can scale it with `kubectl`

**Comment by ngtuna** [comment]
To be exact, I implemented kompose convert --rc <replica>.

Adding replicas count was added in our shared document so I implemented it. This is a tiny change in code and also in user experience which instead of specifying --rc only user can also directly define number of replica with  --rc <replica number>. I see it has benefit for example in case of doing pipe with kubectl. After that, user can also verify and reset replicas by editing rc files. Other hand, it also has a drawback that replica number is set equally to all pods/containers.
