### ISSUE TITLE
Sometimes redundant services are printed/converted in `kompose convert`

### ISSUE THREAD

**Issue by janetkuo** [skippbox/kompose2#20]
Note that there's a redundant `file "web-svc.json" created` message. 

```console 
➜ examples(master)$ ../kompose convert 
file "web-rc.json" created
file "web-svc.json" created
file "redis-rc.json" created
file "web-svc.json" created
file "redis-svc.json" created

➜ examples(master)$ ../kompose convert 
file "redis-rc.json" created
file "web-rc.json" created
file "redis-svc.json" created
file "web-svc.json" created
```

**Comment by ngtuna** [comment]
Yup. Also I have to re-structure convert function. It's too long and difficult to follow somehow.

**Comment by ngtuna** [comment]
Done. Convert function is now more easier to keep track. Issue is also fixed by https://github.com/skippbox/kompose2/commit/2e986b61e7d80617fb29265d70cf167ee1fa4990
