### ISSUE TITLE
Default controller object is always generated.

### ISSUE THREAD

**Issue by kadel** [skippbox/kompose2#33]
Right now default controller is always generated. 
When I do `kompose convert --replicaset` I get Services, Deployments and ReplicaSets.
I think that this is little bit confusing (even if they are in different files).
When I run above command I would expect only Services and ReplicaSets. In most cases you need only one controller object.

When I do `kompose convert --replicaset --deployment` than I would expect both (ReplicaSets and Deployments)

**Comment by runseb** [comment]
yes confirmed:

```
$ kompose convert --rs
file "toto-replicaset.json" created
file "toto-rc.json" created
sebair: kompose2 (master)$ kompose convert --rs --d
file "toto-deployment.json" created
file "toto-replicaset.json" created
file "toto-rc.json" created
```

Even though the default has now changed. It generates deployments and services.
